### ISSUE TITLE
Front end forms - no styling

### ISSUE THREAD

**Issue by ruudvh** [WebDevStudios/CollabPress#87]
The forms on the front-end, such as Add or Edit Project, have no styling attached to them. It seems that WordPress automatically grabs the styling from wp-admin.css, which is not loaded in the front-end.

Adding the following to CollabPress css's files will solve the issue, and make the forms nice and beautiful again. (Not sure of all classes are needed).

``` css
.form-table {
    border-collapse: collapse;
    margin-top: 0.5em;
    width: 100%;
    margin-bottom: -8px;
    clear: both;
}

.form-table td {
    margin-bottom: 9px;
    padding: 8px 10px;
    line-height: 20px;
    font-size: 12px;
}

.form-table th,
.form-wrap label {
    font-weight: normal;
    text-shadow: #fff 0 1px 0;
}

.form-table th {
    vertical-align: top;
    text-align: left;
    padding: 10px;
    width: 200px;
}

.form-table th.th-full {
    width: auto;
}

.form-table div.color-option {
    display: block;
    clear: both;
    margin-top: 12px;
}

.form-table input.tog {
    margin-top: 2px;
    margin-right: 2px;
    float: left;
}

.form-table td p {
    margin-top: 4px;
}

.form-table table.color-palette {
    vertical-align: bottom;
    float: left;
    margin: -12px 3px 11px;
}

.form-table .color-palette td {
    border-width: 1px 1px 0;
    border-style: solid solid none;
    height: 10px;
    line-height: 20px;
    width: 10px;
}
```
