### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by ruudvh** [WebDevStudios/CollabPress#88]
This is not an issue, more like an enhancement.
But a progress bar for the project, probably based on the task added vs tasks completed, would be a great enhancement to the project.

Something like this.
PHP:

``` php
/**
* Count all tasks for specific project and display a progressbar
*/
function cp_progressbar_tasks( $project_id = 0 ){
    global $wpdb;
    $meta_key = '_cp-project-id';
    $meta_value = $project_id;
    $post_type = 'cp-tasks';

    $completedtasks_sql = "SELECT p.ID
    FROM $wpdb->postmeta pm
    JOIN $wpdb->posts p ON (p.ID = pm.post_id)
    WHERE pm.meta_key = '$meta_key'
    AND pm.meta_value = '$meta_value'
    AND p.post_type = '$post_type'
    AND p.post_status = 'publish';
    ";
    $completedtasks = $wpdb->get_col($wpdb->prepare($completedtasks_sql));

    $task_status_list = array();
    foreach ( $completedtasks as $item ) {
        $task_status = cp_get_task_status( $item );
        $task_status_list[] = $task_status;
    }

    $totaltasks = count ($task_status_list);
    $completedtasks = count( array_keys( $task_status_list, "complete" ));

    if ( $totaltasks > 0 AND $completedtasks !== $totaltasks ) {
        $result = '<div id="progress-bar" class="all-rounded">';
        $result .= '<div id="progress-bar-percentage" class="all-rounded" style="width: ';
        $result .= (($completedtasks / $totaltasks) * 100);
        $result .= '%">';
        $result .= '<span>';
        $result .= (($completedtasks / $totaltasks) * 100);
        $result .= '%</span>';
        $result .= '</div></div>';
        echo $result;
    } elseif ( $totaltasks > 0 AND $completedtasks == $totaltasks ) {
        $result = '<div id="progress-bar" class="all-rounded">';
        $result .= '<div id="progress-bar-percentage" class="all-rounded" style="width: 100%">';
        $result .= '<span>All task have been completed!</span>';
        $result .= '</div></div>';
        echo $result;
    }
}
```

CSS:

``` CSS
/* Progress Bar ---------------------------------------- */
.project-progress {
    float: right;
    margin: 1.71429rem 0;
    width: 275px;
    margin-bottom: 10px;
}
.project-progress-dashboard {
    width: 100px;
    margin-bottom: -5px;
}
.all-rounded {
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
}
.spacer {
    display: block;
}
#progress-bar {
    width: 100%;
    background: #cccccc;
    position: relative;
}
#progress-bar-percentage {
    background: #3063A5;
    color: #FFF;
    text-align: center;
    height: 20px;
}
#progress-bar-percentage span {
    display: inline-block;
    position: absolute;
    width: 100%;
    left: 0;
}
```

![progress](https://f.cloud.github.com/assets/4691760/665108/735be064-d794-11e2-9bd4-c6de12b1e0a1.png)

I'm not a programmer, so please excuse my mistakes.
